### ISSUE TITLE
Blank space on RHS when close icon aligned left

### ISSUE THREAD

**Issue by othbert** [vincenzocaselli/opendesktop-dark-wd#1]
Hi, firstly thanks for the window decoration theme, I love it!

I noticed a small issue with the titlebar when the icons are left aligned, where a small gap arises on the right hand side.
![image](https://github.com/vincenzocaselli/opendesktop-dark-wd/assets/6048867/675e3617-9a75-425a-8090-07c4caea4cff)
This is with the borders set to theme default.
Strangely, when the icons are on the right, there are no gaps on the left.

When set to oversized borders, the gap becomes easier to see, that it actually appears on both sides.
![image](https://github.com/vincenzocaselli/opendesktop-dark-wd/assets/6048867/12947cc8-c5b3-40f8-a96a-b684ed8b7f15)

This is on Plasma 5.27.10, Qt 5.15.12, please let me know if I can help by providing any other info!
Thanks!

**Comment by othbert** [comment]
Oh I see now this is/was intentional in the decoration.svg... hmm maybe I will try with your previous svgs in the commit history and can close it. Thanks!

**Comment by vincenzocaselli** [comment]
Hi @othbert thank you for your compliments!
Indeed I am quite a newbie in designing Linux themes, so I played around just to make it work for my usual layout choices.
I don't remember why I changed it in that commit: most probably it wasn't working correctly before.
But I will try to find the time to investigate the problem you mentioned.
Thank you very much!

**Comment by othbert** [comment]
Thanks for taking a look! I also tried to modify it myself with inkscape so I could submit a PR, but I am definitely a theme newbie myself! Nothing I tried managed to work properly, I think perhaps it's a combination of the svg and the padding or borders or... something :)
Again, thanks, the theme is still great, I love the bright highlight on the active, so much more usable than most themes!
